#!/bin/sh
PATH=$PATH:/usr/local/bin:/usr/local/sbin

# prepare the formatter
# swiftformat

# format code
git status -s | grep '^\(A\s\|M\s\).*\.swift.*$' | cut -c3- | while read line; do
  swiftformat --config "config.swiftformat" ${line};
  git add $line;
done
